apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: ClusterIP # Exposes the service on a cluster-internal IP
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 8888 # Port that the service will listen on
      targetPort: 8888 # Port that the pod accepts traffic on
